### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by erguotou520** [yakumioto/drone-serverchan#1]
发现各种文档上image都是`yakumioto/serverchan`，但该image在hub上其实是没有的，真正的名字应该是yakumioto/drone-serverchan，所以麻烦更新下文档，避免后来人迷路。包括Github文档，Drone plugin文档等。感谢作者付出。

**Comment by erguotou520** [comment]
另外问下如果我要拿到构建结果怎么取？

**Comment by yakumioto** [comment]
哈哈哈, 感谢提醒.

另外不太明白你说的返回构建结果是什么意思.

如果是想返回运行到 某个 pipeline 错误的信息, 根据我看的文档里好像没有相关的介绍, 可以去 drone 下发个 issues 看看.

我一般都是返回成功或错误的自定义输出. 让自己知道出错了, 然后上网站查看具体错误信息.

**Comment by erguotou520** [comment]
比如slack插件的template支持这样的结果
```
template: >
  <strong>{{ uppercasefirst build.status }}</strong> <a href=\"{{ system.link_url }}/{{ repo.owner }}/{{ repo.name }}/{{ build.number }}\">{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}</a> ({{ build.branch }}) by {{ build.author }} in {{ duration build.started_at build.finished_at }} </br> - {{ build.message }} {{#success build.status}} It works {{/success}}
```
我可以显示出本次构建的所有信息。实现可以参考下
https://github.com/drone-plugins/drone-slack/blob/master/plugin.go

**Comment by yakumioto** [comment]
看了一下, 好像是定义了一堆的环境变量, 然后用了个模板, 我觉得这样有点复杂化了. 

用这个插件的话 `desp` 字段可以自定义 md 格式的输出, 我觉得这样会比较简单.

**Comment by erguotou520** [comment]
但是没法获取构建结果，发送的结果比较单一

**Comment by yakumioto** [comment]
@erguotou520 看到相关东西了, 这个东西可以加, 哈哈哈.

**Comment by erguotou520** [comment]
好的，麻烦了

**Comment by erguotou520** [comment]
最近又看了下，应该可以直接用这些环境变量
```
DRONE_BUILD_ACTION
DRONE_BUILD_CREATED
DRONE_BUILD_EVENT
DRONE_BUILD_FINISHED
DRONE_BUILD_NUMBER
DRONE_BUILD_PARENT
DRONE_BUILD_STARTED
DRONE_BUILD_STATUS
```
